"""quantity >= 1 constraint

Revision ID: 455779e2afb6
Revises: 6a64f01b2875
Create Date: 2026-04-05 21:06:31.165996

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "455779e2afb6"
down_revision: Union[str, Sequence[str], None] = "6a64f01b2875"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        constraint_name="quantity_ge_1", table_name="order", condition="quantity >= 1"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("quantity_ge_1", table_name="order", type_="check")
    # ### end Alembic commands ###
